[package]
name = "clearcomm-implement"
version = "0.1.0"
authors = ["Andreas Schmidt <lehre@netzdoktor.eu>"]
edition = "2021"

[dependencies]
clearcomm = { path = "../clearcomm" }
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }
color-eyre = "0.6.2"